################################################################################
MLI_FILE		= cordova_email_composer.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-email-composer
################################################################################
